### ISSUE TITLE
mixin has `when` is not support

### ISSUE THREAD

**Issue by xiaoping0x** [ekryski/less2sass#16] opened 2016-11-29 01:31 UTC
.setArrow($direction, $arrowsize, $borderColor, $borderWidth) when ($direction = top) {
    ._setArrow($arrowsize, $borderColor, $borderWidth);
    transform: matrix(0.71,-0.71,0.71,0.71,0,0); // rotate(-45deg)
}

**Comment by ekryski** [comment] 2017-03-31 20:40
Duplicate of #11

**Closed by ekryski** 2017-03-31 20:40 UTC
